require('./images/background.jpg')
require('./images/magnifying-glass.png')
require('./images/red-dots.png')
require('./images/logo.png')
require('./skeleton.scss')
require('./style.scss')
require('./scripts/script.js')
