require('./images/background.jpg')
require('./images/magnifying-glass.png')
require('./images/red-dots.png')
require('./images/logo.png')
require('./styles/skeleton.scss')
require('./styles/main.scss')
require('./styles/images.scss')
require('./scripts/script.js')
